"""empty message

Revision ID: dcc789dfd762
Revises: 
Create Date: 2018-09-23 10:09:17.616691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc789dfd762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bday', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('jday', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'jday')
    op.drop_column('user', 'bday')
    # ### end Alembic commands ###
